version: "3.8"

services:

  sensor-web:
    build: ./sensor-web
    container_name: sensor-web
    ports:
      - "80:80"
    restart: always
    environment:
      - VITE_API_URL=http://sensor-api:8080/api/data
    depends_on:
      - sensor-api
    networks:
        - sensor_monitoring_network

  sensor-emulator:
    build: ./sensor-emulator
    container_name: sensor-emulator
    restart: always
    environment:
      - API_URL=http://sensor-api:8080/api/data
    depends_on:
      - sensor-api
    networks:
      - sensor_monitoring_network

  sensor-api:
    build: ./sensor-api
    container_name: sensor-api
    restart: always
    ports:
      - "8080:8080"
    networks:
      - sensor_monitoring_network
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sensor-monitoring
    ports:
      - "5432:5432"
    networks:
      - sensor_monitoring_network

networks:
  sensor_monitoring_network:
    driver: bridge
